name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Secret Detection: Gitleaks"
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "SAST: ShellCheck Linter"
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          shellcheck sys_health.sh

      - name: "Lint: Hadolint Dockerfile Linter"
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: Build Docker Image
        run: docker build -t cloud-ops-health:test .

      - name: "Security Scan: Aqua Trivy Vulnerability Gate"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cloud-ops-health:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Run Container Smoke Test
        run: docker run --rm cloud-ops-health:test
